// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB13hWJfTWLu_hOIdDDgFvE5fBUr_QdPW0',
    appId: '1:392000015418:web:588952ec999ccdc18af903',
    messagingSenderId: '392000015418',
    projectId: 'todo-app-ee652',
    authDomain: 'todo-app-ee652.firebaseapp.com',
    storageBucket: 'todo-app-ee652.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDpgKDAbnlZ84vJr1Zh0TpL2rQB_Sqhuw',
    appId: '1:392000015418:android:e30dea287bbd9a6f8af903',
    messagingSenderId: '392000015418',
    projectId: 'todo-app-ee652',
    storageBucket: 'todo-app-ee652.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWmCvjvco2of8dtapg2k3qBrTX3YkeysU',
    appId: '1:392000015418:ios:6ac5e13469462da38af903',
    messagingSenderId: '392000015418',
    projectId: 'todo-app-ee652',
    storageBucket: 'todo-app-ee652.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
